version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0-rc2
    container_name: §§INSTANCE-elasticsearch
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT2:9200"
      - "§§PORT3:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes_from:
      - §§INSTANCE-elasticstack-data
      

  §§INSTANCE-kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0-rc2
    container_name: §§INSTANCE-kibana
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-elasticsearch:elasticsearch
    ports:
      - "§§PORT1:5601"
    depends_on:
      - §§INSTANCE-elasticsearch
      - §§INSTANCE-elasticstack-data
    volumes_from: 
      - §§INSTANCE-elasticstack-data
      
  §§INSTANCE-elasticstack-data:
    image: busybox
    container_name: §§INSTANCE-elasticstack-data
    networks:
      - bibbox-default-network
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./var/config/logstash:/etc/logstash/conf.d
      - ./var/config/kibana:/opt/kibana/config