version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-elasticsearch:
    image: elasticsearch
    container_name: §§INSTANCE-elasticsearch
    restart: unless-stopped
    networks:
      - bibbox-default-network
    ports:
      - "§§PORT3:9200"
      - "§§PORT4:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      
  §§INSTANCE-logstash:
    image: logstash
    container_name: §§INSTANCE-logstash
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-elasticsearch:elasticsearch
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "§§PORT2:5000"
    depends_on:
      - §§INSTANCE-elasticsearch
      - §§INSTANCE-elasticstack-data
    volumes_from: 
      - §§INSTANCE-elasticstack-data
      
  §§INSTANCE-kibana:
    image: kibana
    container_name: §§INSTANCE-kibana
    restart: unless-stopped
    networks:
      - bibbox-default-network
    links:
      - §§INSTANCE-elasticsearch:elasticsearch
    ports:
      - "§§PORT1:5601"
    depends_on:
      - §§INSTANCE-elasticsearch
      - §§INSTANCE-elasticstack-data
    volumes_from: 
      - §§INSTANCE-elasticstack-data
      
  §§INSTANCE-elasticstack-data:
    image: busybox
    container_name: §§INSTANCE-elasticstack-data
    networks:
      - bibbox-default-network
    volumes:
      - ./var/config/logstash:/etc/logstash/conf.d
      - ./var/config/kibana:/opt/kibana/config