version: '3'
networks:
  bibbox-default-network:
    external: true
services:
  local-elasticsearch:
    container_name: local-elasticsearch
    environment:
      - node.name=local-elasticsearch
      - cluster.initial_master_nodes=local-elasticsearch
      - ELASTIC_PASSWORD=elastic
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    networks:
    - bibbox-default-network
    ports:
    - 9300:9300 
    restart: unless-stopped
    volumes:
    - ./data:/usr/share/elasticsearch/data
    - ./config/logstash:/etc/logstash/conf.d
  
  local-kibana:
    container_name: local-kibana
    depends_on:
    - "local-elasticsearch"
    image: docker.elastic.co/kibana/kibana:8.1.0
    links:
    - "local-elasticsearch:elasticsearch"
    environment:
      - SERVERNAME=local-kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin
      - ELASTICSEARCH_PASSWORD=elastic
    networks:
    - bibbox-default-network
    ports:
    - 5601:5601
    restart: unless-stopped
    volumes:
    - ./config/logstash:/etc/logstash/conf.d

